name: Orde
favicon: null
layout_spectrum: 0.4988
typography_spectrum: 0.24729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#005e84'
    - '#93a6be'
    - '#e1e5eb'
    - '#5391ab'
  brandStrength: 0.5
  lightness: 0.09043243248015642
  saturation: 0.3776023758109659
  rhythmicContrast: 0.04459291440434754
purpose: []
